openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  /user/register:
    post:
      summary: ユーザ登録
      operationId: userRegister
      responses:
        "200":
          description: 正常に処理できた
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    APIResponse:
      type: object
      properties:
        original:
          $ref: "#/components/schemas/OriginalResponse"
        common:
          $ref: "#/components/schemas/CommonResponse"
    OriginalResponse:
      type: object
      properties:
        user_register:
          $ref: "#/components/schemas/UserRegisterResponseContent"
    CommonResponse:
      type: object
      properties:
        delete:
          type: object
          properties:
            user_coin:
              type: array
              items:
                $ref: "#/components/schemas/UserCoin"
        update:
          type: object
          properties:
            user_coin:
              type: array
              items:
                $ref: "#/components/schemas/UserCoin"
    UserRegisterResponseContent:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
    UserCoin:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        currency:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
