// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/yamato0204/cache-server-golang/cmd/di/provider"
	"github.com/yamato0204/cache-server-golang/internal/handler"
	"github.com/yamato0204/cache-server-golang/internal/handler/api"
	"github.com/yamato0204/cache-server-golang/internal/service"
	"github.com/yamato0204/cache-server-golang/internal/usecase"
)

// Injectors from wire.go:

func Inject() (*provider.GameServer, func(), error) {
	int64_2 := provider.ProvideUserID()
	userRegisterService := service.NewUserRegisterService(int64_2)
	userUsecase := usecase.NewUserUsecase(userRegisterService)
	userHandler := api.NewUserHandler(userUsecase)
	baseHandler := handler.NewBaseHandler(userHandler)
	router := handler.NewRouter(baseHandler)
	gameServer := provider.NewGameServer(router)
	return gameServer, func() {
	}, nil
}
